### ISSUE TITLE
Does not show attributes in the attributes-section when adding / editing a combined value

### ISSUE THREAD

**Issue by comede** [MetaModels/attribute_combinedvalues#10]
comparing with the alias-attribute i am missing one line of code at the end of the "getOptions"-Function in the Subscriber.php (composer/vendor/metamodels/attribute_combinedvalues/src/DcGeneral/Events/Table/Attribute/CombinedValues/Subscriber.php):

    $event->setOptions($result);

After adding this line, in works.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@comede could you please have a final look at this and tell if your issue has been resolved?
