### ISSUE TITLE
Aktualisierung erzwingen hat keinen Effekt, wenn das Attribut neu gesetzt ist.

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_combinedvalues#11]
MM wird schon benutzt. Attribut wird ergänzt. Es wird erst ein Wert gesetzt, wenn man an den zu kombinierenden Einträgen etwas ändert. Nach dem ersten mal klappt es dann auch immer... Ist einfach etwas unschön und unbequem.. daher keine Hohe Prio.

**Comment by xantippe** [comment]
... Du meinst, wenn das Attribut [combinedvalues] "nachträglich" eingefügt wird, dann wird es nicht automatisch "befüllt"?

**Comment by MacKP** [comment]
Jap. Ist ein etwas komisches Verhalten insgesammt. Bei meiner letzten größeren Installation hatte ich deswegen verschiedenes durchprobiert: Mit oder ohne 'immer neu generieren' etc. hat nicht unbedingt funktioniert.. war alles etwas strange.

**Comment by xantippe** [comment]
ich glaube, das 'immer neu generieren' benötigt einen geänderten Wert als "Trigger" - ggf. wäre es möglich zu implementieren "wenn [combinedvalues] leer und 'immer neu generieren' aktiv, dann erstelle neuen Wert auch ohne Änderung eines Einzelwertes"

**Comment by discordier** [comment]
dc-general muss das DCA Eval Attribut `always_save` verstehen, bislang ist dies noch nicht der Fall.

**Comment by xantippe** [comment]
"weiß" der DCG davon? oder Ticket dazu?

**Comment by discordier** [comment]
contao-community-alliance/dc-general#174
