### ISSUE TITLE
Combined attribute charges http://php.net/sprintf page for each added attribute 

### ISSUE THREAD

**Issue by JLBA** [MetaModels/attribute_combinedvalues#13]
Hi,

A strange thing under Mac OS X 10.9 with Safari. 
In BE, when creating or modifying a combined attribute, we are redirect to http://php.net/sprintf each time we add or modify an attribute (in same tab or a new tab).

I have not the pb with Firefox nor Chromium.

**Comment by stefanheimes** [comment]
Hmm maybe it is a JavaScript Error. Can u check the Console for it.

**Comment by xantippe** [comment]
@JLBA pls look at your PMs at community..

**Comment by JLBA** [comment]
Sorry for no answering earlier. I wasn't in front of my computer yesterday.

Today, I got the same problem in FF 45.0 and Chromium 50/0.2653.0 Mac.

When  mouse:over on Save, Save and close etc… buttons, the link is http://php.net/sprintf

I've opened web inspector and see this javascript message in FF : 
`L'utilisation de « getAttributeNode() » est obsolète. Utiliser « getAttribute() » à la place. 8b1f17b76ee8.js:3:21787` (Sorry, in french).

**Comment by JLBA** [comment]
Hi,

**The problem only occurs when Contao's backend is in french language, not when in english for example.
**
Have a nice monday.

**Comment by discordier** [comment]
Seems to be a problem in the french translation then.

**Comment by discordier** [comment]
Ah, in https://github.com/MetaModels/attribute_combinedvalues/commit/c54170d3c05df9317a9732b9807ea461544b2524#diff-d17eee7175573fa22605626af8c5ae4eR17 seems to be the problem, in there we have an additional space in the closing `</a>`.
@JLBA Could you please check if removing that one solves the problem for you?
If so, some french translator should remove the space from the translation (@lucina could you take care of this? You are the coordinator of the French translation)

**Comment by zonky2** [comment]
@lucina had fixed at transifex

**Comment by kikmedia** [comment]
Been there, done that. Should be fixed after pulling french translations.

**Comment by JLBA** [comment]
Hello everyone,
@Discordier Sorry for being late to test and answer, I haven't seen your question.
I confirm this is the problem and the solution but there are 4 files to correct : 
- modules/metamodelsattribute_combinevalues/languages/fr/tl_metamodel_attribute.php
- modules/metamodelsattribute_translatedcombinedvalues/…
- composer/vendor/metamodels/attribute_combinedvalues/contao/languages/fr/tl_metamodel_attribute.php
- composer/vendor/metamodels/attribute_translatedcombinedvalues/…
The problem persists until the four files are corrected.

**Comment by discordier** [comment]
@kikmedia Could you check above mentioned translations and correct if needed?
