### ISSUE TITLE
Bug at select attribute with MCW

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_combinedvalues#20]
Bug at select attribute with MCW in properties of attribute:

if we add a second row, the select shows only a "-" - after save I see all attributes at select

**Comment by discordier** [comment]
What dows the AJAX result in? Are the options present in there?

**Comment by zonky2** [comment]
its a bug in MCW https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/45 with chosen

**Comment by zonky2** [comment]
fixed in https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/85
