### ISSUE TITLE
Feld in DB ändern zu TEXT

### ISSUE THREAD

**Issue by emkayy** [MetaModels/attribute_combinedvalues#7]
Bitte den Typ von varchar(255) auf text ändern.
Beim kombinieren von mehreren Feldern (es reichen ja theoretisch schon 2 varchar(255) Felder) oder text Attributen, werden diese abgeschnitten. Das ist natürlich nicht schön! :)

**Comment by xantippe** [comment]
Gegenüber dem berechtigtem technischen Einwand steht m.E. die Frage, ob das Sinnvoll ist...

Da der Alias üblicher Weise hier und da in der URL auftaucht, ist die Begrenzung derselben im Blick zu behalten
* W3: 255 Byte
* IE: max 2.038 Zeichen
* SEO: etwa max 100 bis 255 Zeichen

https://de.wikipedia.org/wiki/Query_String

**Comment by MacKP** [comment]
Sinnvoll ist das schon. Vor allem auch, da man das Feld für vieles nutzen kann. Nicht nur als Grundlage für den Alias.

**Comment by stefanheimes** [comment]
Für Alias gebe ich @xantippe recht, aber das hier ist kein Alias, es fehlen auch die Funktion um daraus ein Alias zu machen, daher können wir das gerne machen, das Problem ist nur wie wir es hinbekommen die bestehenden Felder auf text umzustellen.

**Comment by xantippe** [comment]
ein "runonce" gibt es wahrscheinlich nicht :-(

**Comment by discordier** [comment]
Keine generische. I'm Core haben wir einen Upgrade handler

**Comment by xantippe** [comment]
aber kann der über das Update per Composer angestossen werden?

**Comment by stefanheimes** [comment]
@discordier Was ist wenn wir das interface für die Attribute erweitern. Wir schreiben da noch ein upgrade function rein. Diese wird aufgerufen über eine runonce im core und direkt alle attribute durch.

Die simple als Basis macht dann nichts und wenn doch was ist, prüfen die Attribute das selber.
Dann könnten wir auch alles nach ziehen und müssen nicht gleich wieder alles anpassen.

**Comment by discordier** [comment]
Ich moechte eigentlich die Interfaces eher verschlanken als noch dicker machen.
Wir sollten aber einen allgemeinen UpgradeHandler bauen, bei welchem sich die Attributshandler registrieren koennen.
Auf diese Weise koennen wir dann die Domains getrennt halten.

**Comment by discordier** [comment]
Upgrade handler has been implemented, could someone please test?

I currently lack an installation with an combinedvalues attribute let alone one configured before the change.

Preferely @emkayy

**Comment by zonky2** [comment]
test with  metamodels/attribute_combinedvalues (dev-hotfix/2.0.0-alpha2 f1a07d8)

before
![shot213](https://cloud.githubusercontent.com/assets/1045318/15673315/3a459bcc-2736-11e6-8e01-a641c9d18840.jpg)

after upddate
![shot214](https://cloud.githubusercontent.com/assets/1045318/15673325/49d39242-2736-11e6-81d4-ac412fbf30bd.jpg)

**Comment by discordier** [comment]
So fix confirmed. :smile:
