### ISSUE TITLE
PHP Deprecated notice:

### ISSUE THREAD

**Issue by ae69** [MetaModels/attribute_combinedvalues#9]
Folgende Fehlermeldung tritt beim Öffnen der Attribute auf:

    PHP Deprecated notice: The Symfony\Component\EventDispatcher\Event::getDispatcher method is deprecated since version 2.4 and will be removed in 3.0. The event dispatcher instance can be received in the listener call instead. in C:\xampp\htdocs\system\modules\symfony-event-dispatcher\classes\Symfony\Component\EventDispatcher\Event.php on line 100 #0 [internal function]:
     __error(16384, 'The Symfony\Com...', 'C:\xampp\htdocs...', 100, Array) #1 C:\xampp\htdocs\system\modules\symfony-event-dispatcher\classes\Symfony\Component\EventDispatcher\Event.php(100): trigger_error('The Symfony\Com...', 16384)

Verwendung:
nightly-tng vom 17-01-2015 und core-hotfix-3.4.1

**Comment by discordier** [comment]
Should be fixed by contao-community-alliance/dc-general@40c85ffe86f90843935ba43acede4e74fe5cfdf2
